from __future__ import annotations

from typing import List, Optional

from platform.backend.schemas import MetricDefinition, MetricLayer


def md(
    name: str,
    description: str,
    *,
    unit: str | None,
    layer: MetricLayer,
    kind: str | None = None,
    osi_layer: int | None = None,
    category: str | None = None,
    tags: Optional[List[str]] = None,
    dimensions: Optional[List[str]] = None,
) -> MetricDefinition:
    return MetricDefinition(
        name=name,
        description=description,
        unit=unit,
        layer=layer,
        kind=kind,
        osi_layer=osi_layer,
        category=category,
        tags=list(tags or []),
        dimensions=list(dimensions or []),
    )


# Canonical observability catalog (OSI 0-7 + control/dataplane + transversal).
# Notes:
# - Some indicators are "derived" (computed from other metrics); they are still included
#   so the API/UI can fully represent the target dashboard taxonomy.
# - Dimensions are suggestions for labeling (src/dst, vrf, prefix, sni, rule_id, etc.).
METRIC_CATALOG: List[MetricDefinition] = [
    # 0) Service / User Experience (E2E)
    md(
        "e2e_path_availability_pct",
        "Disponibilidade do caminho (sucesso de probes sintéticos)",
        unit="%",
        layer="service",
        kind="ratio",
        osi_layer=0,
        category="e2e",
        dimensions=["src", "dst", "service"],
    ),
    md(
        "e2e_latency_ms_p50",
        "Latência E2E p50",
        unit="ms",
        layer="service",
        kind="summary",
        osi_layer=0,
        category="e2e",
        dimensions=["src", "dst", "service"],
    ),
    md(
        "e2e_latency_ms_p95",
        "Latência E2E p95",
        unit="ms",
        layer="service",
        kind="summary",
        osi_layer=0,
        category="e2e",
        dimensions=["src", "dst", "service"],
    ),
    md(
        "e2e_latency_ms_p99",
        "Latência E2E p99",
        unit="ms",
        layer="service",
        kind="summary",
        osi_layer=0,
        category="e2e",
        dimensions=["src", "dst", "service"],
    ),
    md(
        "e2e_jitter_ms_p95",
        "Jitter E2E p95",
        unit="ms",
        layer="service",
        kind="summary",
        osi_layer=0,
        category="e2e",
        dimensions=["src", "dst", "service"],
    ),
    md(
        "e2e_loss_pct",
        "Perda E2E",
        unit="%",
        layer="service",
        kind="ratio",
        osi_layer=0,
        category="e2e",
        dimensions=["src", "dst", "service"],
    ),
    md(
        "path_changes_total",
        "Mudanças de rota (path changes / ECMP hash changes)",
        unit="count",
        layer="service",
        kind="counter",
        osi_layer=0,
        category="e2e",
        dimensions=["src", "dst", "service"],
    ),
    md(
        "mttd_sec",
        "Tempo médio de detecção (MTTD)",
        unit="s",
        layer="service",
        kind="derived",
        osi_layer=0,
        category="reliability",
        dimensions=["service", "incident_id"],
    ),
    md(
        "mttr_sec",
        "Tempo médio de restauração (MTTR)",
        unit="s",
        layer="service",
        kind="derived",
        osi_layer=0,
        category="reliability",
        dimensions=["service", "incident_id"],
    ),
    md(
        "worst_path_score",
        "Score derivado para rankear piores caminhos (loss/latency/jitter)",
        unit=None,
        layer="service",
        kind="derived",
        osi_layer=0,
        category="e2e",
        dimensions=["src", "dst", "service"],
    ),

    # 1) Physical (L1)
    md(
        "if_link_up",
        "Status do link (up=1/down=0)",
        unit="bool",
        layer="physical",
        kind="gauge",
        osi_layer=1,
        category="health",
        dimensions=["node", "interface"],
    ),
    md(
        "if_flaps_total",
        "Contagem de flaps (up/down)",
        unit="count",
        layer="physical",
        kind="counter",
        osi_layer=1,
        category="health",
        dimensions=["node", "interface"],
    ),
    md(
        "if_speed_mbps",
        "Velocidade negociada",
        unit="Mbps",
        layer="physical",
        kind="gauge",
        osi_layer=1,
        category="capacity",
        dimensions=["node", "interface"],
    ),
    md(
        "if_duplex_mismatch",
        "Mismatch de duplex (1=sim)",
        unit="bool",
        layer="physical",
        kind="gauge",
        osi_layer=1,
        category="health",
        dimensions=["node", "interface"],
    ),
    md(
        "if_in_bps",
        "Tráfego de entrada (bits/s)",
        unit="bps",
        layer="physical",
        kind="gauge",
        osi_layer=1,
        category="capacity",
        dimensions=["node", "interface"],
    ),
    md(
        "if_out_bps",
        "Tráfego de saída (bits/s)",
        unit="bps",
        layer="physical",
        kind="gauge",
        osi_layer=1,
        category="capacity",
        dimensions=["node", "interface"],
    ),
    md(
        "if_in_bps_p95",
        "Utilização de entrada p95 (bits/s)",
        unit="bps",
        layer="physical",
        kind="derived",
        osi_layer=1,
        category="capacity",
        dimensions=["node", "interface"],
    ),
    md(
        "if_in_bps_p99",
        "Utilização de entrada p99 (bits/s)",
        unit="bps",
        layer="physical",
        kind="derived",
        osi_layer=1,
        category="capacity",
        dimensions=["node", "interface"],
    ),
    md(
        "if_out_bps_p95",
        "Utilização de saída p95 (bits/s)",
        unit="bps",
        layer="physical",
        kind="derived",
        osi_layer=1,
        category="capacity",
        dimensions=["node", "interface"],
    ),
    md(
        "if_out_bps_p99",
        "Utilização de saída p99 (bits/s)",
        unit="bps",
        layer="physical",
        kind="derived",
        osi_layer=1,
        category="capacity",
        dimensions=["node", "interface"],
    ),
    # Physical errors/drops
    md("if_errors", "Interface errors", unit="count", layer="physical", kind="counter", osi_layer=1, category="errors", dimensions=["node", "interface"]),
    md("if_discards", "Interface discards", unit="count", layer="physical", kind="counter", osi_layer=1, category="errors", dimensions=["node", "interface"]),
    md("if_crc_errors", "CRC errors", unit="count", layer="physical", kind="counter", osi_layer=1, category="errors", dimensions=["node", "interface"]),
    md("if_fcs_errors_total", "FCS errors", unit="count", layer="physical", kind="counter", osi_layer=1, category="errors", dimensions=["node", "interface"]),
    md("if_alignment_errors_total", "Alignment errors", unit="count", layer="physical", kind="counter", osi_layer=1, category="errors", dimensions=["node", "interface"]),
    md("if_symbol_errors_total", "Symbol errors", unit="count", layer="physical", kind="counter", osi_layer=1, category="errors", dimensions=["node", "interface"]),
    md(
        "if_physical_drops_total",
        "Drops físicos (quando possível separar de congestionamento)",
        unit="count",
        layer="physical",
        kind="counter",
        osi_layer=1,
        category="errors",
        dimensions=["node", "interface"],
    ),
    # Optical / transceivers
    md("if_optic_rx_dbm", "Optical RX power", unit="dBm", layer="physical", kind="gauge", osi_layer=1, category="health", dimensions=["node", "interface"]),
    md("if_optic_tx_dbm", "Optical TX power", unit="dBm", layer="physical", kind="gauge", osi_layer=1, category="health", dimensions=["node", "interface"]),
    md("if_optic_osnr_db", "Optical OSNR", unit="dB", layer="physical", kind="gauge", osi_layer=1, category="health", dimensions=["node", "interface"]),
    md("if_optic_bias_ma", "Optical bias current", unit="mA", layer="physical", kind="gauge", osi_layer=1, category="health", dimensions=["node", "interface"]),
    md("if_optic_temp_c", "Optical module temperature", unit="C", layer="physical", kind="gauge", osi_layer=1, category="health", dimensions=["node", "interface"]),
    md(
        "if_optic_threshold_violations_total",
        "Optical threshold violations",
        unit="count",
        layer="physical",
        kind="counter",
        osi_layer=1,
        category="health",
        dimensions=["node", "interface"],
    ),
    md("if_temp_c", "Interface temperature", unit="C", layer="physical", kind="gauge", osi_layer=1, category="health", dimensions=["node", "interface"]),
    md(
        "if_mtu_effective_bytes",
        "MTU efetivo (detecção de inconsistências)",
        unit="bytes",
        layer="physical",
        kind="gauge",
        osi_layer=1,
        category="health",
        dimensions=["node", "interface"],
    ),
    # PoE
    md("poe_power_w", "Consumo PoE", unit="W", layer="physical", kind="gauge", osi_layer=1, category="capacity", dimensions=["node", "interface"]),
    md("poe_events_total", "Eventos PoE", unit="count", layer="physical", kind="counter", osi_layer=1, category="health", dimensions=["node", "interface"]),
    md("poe_budget_w", "Budget PoE", unit="W", layer="physical", kind="gauge", osi_layer=1, category="capacity", dimensions=["node"]),

    # 2) Link (L2)
    md("mac_table_size", "Tamanho da MAC table", unit="count", layer="link", kind="gauge", osi_layer=2, category="l2", dimensions=["node", "vlan"]),
    md("mac_churn_rate", "MAC churn rate", unit="count/s", layer="link", kind="derived", osi_layer=2, category="l2", dimensions=["node", "vlan"]),
    md("mac_moves_total", "MAC moves", unit="count", layer="link", kind="counter", osi_layer=2, category="l2", dimensions=["node", "vlan"]),
    md("stp_root_changes_total", "STP root changes", unit="count", layer="link", kind="counter", osi_layer=2, category="l2", dimensions=["node", "instance"]),
    md("stp_topology_changes_total", "STP topology changes", unit="count", layer="link", kind="counter", osi_layer=2, category="l2", dimensions=["node", "instance"]),
    md("stp_blocked_ports", "STP blocked ports", unit="count", layer="link", kind="gauge", osi_layer=2, category="l2", dimensions=["node"]),
    md("lacp_members_up", "LACP members up", unit="count", layer="link", kind="gauge", osi_layer=2, category="l2", dimensions=["node", "portchannel"]),
    md("lacp_members_down", "LACP members down", unit="count", layer="link", kind="gauge", osi_layer=2, category="l2", dimensions=["node", "portchannel"]),
    md("lacp_imbalance_pct", "LACP imbalance", unit="%", layer="link", kind="ratio", osi_layer=2, category="capacity", dimensions=["node", "portchannel"]),
    md("lacp_renegotiations_total", "LACP renegotiations", unit="count", layer="link", kind="counter", osi_layer=2, category="l2", dimensions=["node", "portchannel"]),
    md("vlan_active_count", "VLANs ativas por trunk", unit="count", layer="link", kind="gauge", osi_layer=2, category="l2", dimensions=["node", "trunk"]),
    md("vlan_allowed_mismatch_total", "Inconsistência de VLANs allowed", unit="count", layer="link", kind="counter", osi_layer=2, category="l2", dimensions=["node", "trunk"]),
    md("vlan_native_mismatch_total", "Inconsistência de VLAN native", unit="count", layer="link", kind="counter", osi_layer=2, category="l2", dimensions=["node", "trunk"]),
    md("bum_rate_pps", "Taxa de BUM (broadcast/multicast/unknown)", unit="pps", layer="link", kind="gauge", osi_layer=2, category="capacity", dimensions=["node", "vlan", "type"]),
    md("bum_peak_pps", "Pico de BUM", unit="pps", layer="link", kind="derived", osi_layer=2, category="capacity", dimensions=["node", "vlan", "type"]),
    md("arp_cache_util_pct", "ARP cache utilization", unit="%", layer="link", kind="ratio", osi_layer=2, category="l2", dimensions=["node", "vrf"]),
    md("arp_miss_rate", "ARP miss rate", unit="count/s", layer="link", kind="derived", osi_layer=2, category="l2", dimensions=["node", "vrf"]),
    md("arp_duplicates_total", "ARP duplicados", unit="count", layer="link", kind="counter", osi_layer=2, category="l2", dimensions=["node", "vrf"]),
    md("arp_gratuitous_spikes_total", "Picos de gratuitous ARP", unit="count", layer="link", kind="counter", osi_layer=2, category="l2", dimensions=["node", "vrf"]),
    md("nd_cache_util_pct", "ND (IPv6) cache utilization", unit="%", layer="link", kind="ratio", osi_layer=2, category="l2", dimensions=["node", "vrf"]),
    md("nd_miss_rate", "ND miss rate", unit="count/s", layer="link", kind="derived", osi_layer=2, category="l2", dimensions=["node", "vrf"]),
    md("nd_duplicates_total", "ND duplicados", unit="count", layer="link", kind="counter", osi_layer=2, category="l2", dimensions=["node", "vrf"]),
    md("lldp_neighbors_expected_pct", "LLDP/CDP expected vs real", unit="%", layer="link", kind="ratio", osi_layer=2, category="l2", dimensions=["node"]),
    md("lldp_drift_total", "LLDP/CDP drift events", unit="count", layer="link", kind="counter", osi_layer=2, category="l2", dimensions=["node"]),
    md("microburst_queue_occupancy_pct_peak", "Microbursts: pico de fila/ocupação", unit="%", layer="link", kind="derived", osi_layer=2, category="capacity", dimensions=["node", "interface", "queue"]),

    # Existing link metrics kept
    md("link_util_pct", "Link utilization", unit="%", layer="link", kind="gauge", osi_layer=2, category="capacity", dimensions=["node", "interface"]),
    md("link_loss_pct", "Link loss", unit="%", layer="link", kind="ratio", osi_layer=2, category="errors", dimensions=["node", "interface"]),
    md("link_jitter_ms", "Link jitter", unit="ms", layer="link", kind="gauge", osi_layer=2, category="performance", dimensions=["node", "interface"]),
    md("queue_occupancy_pct", "Queue occupancy", unit="%", layer="link", kind="gauge", osi_layer=2, category="capacity", dimensions=["node", "interface", "queue", "qos_class"]),
    md("queue_drops", "Queue drops", unit="count", layer="link", kind="counter", osi_layer=2, category="errors", dimensions=["node", "interface", "queue", "qos_class"]),
    md("ecn_marked_pct", "ECN marked traffic", unit="%", layer="link", kind="ratio", osi_layer=2, category="capacity", dimensions=["node", "interface", "qos_class"]),

    # 3) Network (L3)
    md("prefix_reachability_pct", "Reachability por prefixo", unit="%", layer="network", kind="ratio", osi_layer=3, category="l3", dimensions=["prefix", "vrf", "tenant", "src", "dst"]),
    md("routing_convergence_ms", "Tempo de convergência de roteamento", unit="ms", layer="network", kind="derived", osi_layer=3, category="l3", dimensions=["protocol", "vrf"]),
    md("route_count", "Route count (total/por AFI/SAFI/VRF)", unit="count", layer="network", kind="gauge", osi_layer=3, category="l3", dimensions=["protocol", "afi", "safi", "vrf"]),
    md("route_churn_rate", "Route churn rate", unit="count/s", layer="network", kind="derived", osi_layer=3, category="l3", dimensions=["protocol", "vrf"]),
    md("bgp_session_up", "BGP session up (1/0)", unit="bool", layer="network", kind="gauge", osi_layer=3, category="routing", dimensions=["peer", "vrf", "afi", "safi"]),
    md("bgp_session_flaps_total", "BGP session flaps", unit="count", layer="network", kind="counter", osi_layer=3, category="routing", dimensions=["peer", "vrf"]),
    md("bgp_updates_total", "BGP updates", unit="count", layer="network", kind="counter", osi_layer=3, category="routing", dimensions=["peer", "vrf", "afi", "safi"]),
    md("bgp_withdraws_total", "BGP withdraws", unit="count", layer="network", kind="counter", osi_layer=3, category="routing", dimensions=["peer", "vrf", "afi", "safi"]),
    md("bgp_prefix_limit_hits_total", "BGP prefix limit hits", unit="count", layer="network", kind="counter", osi_layer=3, category="routing", dimensions=["peer", "vrf"]),
    md("bgp_as_path_changes_total", "BGP AS-path changes", unit="count", layer="network", kind="counter", osi_layer=3, category="routing", dimensions=["prefix", "peer", "vrf"]),
    md("ospf_session_up", "OSPF adjacency up (1/0)", unit="bool", layer="network", kind="gauge", osi_layer=3, category="routing", dimensions=["neighbor", "area", "vrf"]),
    md("ospf_flaps_total", "OSPF adjacency flaps", unit="count", layer="network", kind="counter", osi_layer=3, category="routing", dimensions=["neighbor", "area", "vrf"]),
    md("isis_session_up", "IS-IS adjacency up (1/0)", unit="bool", layer="network", kind="gauge", osi_layer=3, category="routing", dimensions=["neighbor", "level", "vrf"]),
    md("isis_flaps_total", "IS-IS adjacency flaps", unit="count", layer="network", kind="counter", osi_layer=3, category="routing", dimensions=["neighbor", "level", "vrf"]),
    md("icmp_unreachable_total", "ICMP unreachable", unit="count", layer="network", kind="counter", osi_layer=3, category="errors", dimensions=["src", "dst", "code"]),
    md("icmp_frag_needed_total", "ICMP frag needed (PMTUD)", unit="count", layer="network", kind="counter", osi_layer=3, category="errors", dimensions=["src", "dst"]),
    md("ip_fragments_total", "IP fragments", unit="count", layer="network", kind="counter", osi_layer=3, category="errors", dimensions=["src", "dst"]),
    md("ip_fragment_drops_total", "Drops por MTU/fragmentação", unit="count", layer="network", kind="counter", osi_layer=3, category="errors", dimensions=["node"]),
    md("dscp_packets_total", "Distribuição DSCP (contagem por classe)", unit="count", layer="network", kind="counter", osi_layer=3, category="qos", dimensions=["dscp", "node", "interface"]),
    md("dscp_remark_events_total", "Eventos de remarking DSCP", unit="count", layer="network", kind="counter", osi_layer=3, category="qos", dimensions=["from", "to", "policy"]),
    md("acl_drops_total", "ACL/Policy drops por regra", unit="count", layer="network", kind="counter", osi_layer=3, category="security", dimensions=["rule_id", "node"]),
    md("tunnel_up", "Tunnel up/down", unit="bool", layer="network", kind="gauge", osi_layer=3, category="overlay", dimensions=["tunnel", "type", "vrf"]),
    md("tunnel_keepalive_loss_total", "Tunnel keepalive loss", unit="count", layer="network", kind="counter", osi_layer=3, category="overlay", dimensions=["tunnel", "type", "vrf"]),
    md("tunnel_encap_errors_total", "Encapsulation errors", unit="count", layer="network", kind="counter", osi_layer=3, category="overlay", dimensions=["tunnel", "type"]),
    md("tunnel_decap_errors_total", "Decapsulation errors", unit="count", layer="network", kind="counter", osi_layer=3, category="overlay", dimensions=["tunnel", "type"]),
    md("vxlan_vni_mapping_ok", "VNI/VRF mapping health", unit="bool", layer="network", kind="gauge", osi_layer=3, category="overlay", dimensions=["vni", "vrf"]),

    # Existing network metrics kept
    md("latency_ms", "Latency", unit="ms", layer="network", kind="gauge", osi_layer=3, category="performance", dimensions=["src", "dst"]),
    md("packet_loss_pct", "Packet loss", unit="%", layer="network", kind="ratio", osi_layer=3, category="performance", dimensions=["src", "dst"]),
    md("jitter_ms", "Jitter", unit="ms", layer="network", kind="gauge", osi_layer=3, category="performance", dimensions=["src", "dst"]),
    md("ttl_expired", "TTL expired events", unit="count", layer="network", kind="counter", osi_layer=3, category="errors", dimensions=["src", "dst"]),
    md("routes_count", "Route entries", unit="count", layer="network", kind="gauge", osi_layer=3, category="routing", dimensions=["node", "vrf"]),
    md("arp_entries", "ARP/ND cache entries", unit="count", layer="network", kind="gauge", osi_layer=3, category="l3", dimensions=["node", "vrf"]),

    # 4) Transport (L4)
    md("tcp_retrans_pct", "TCP retransmissions (%)", unit="%", layer="transport", kind="ratio", osi_layer=4, category="transport", dimensions=["src", "dst", "flow"]),
    md("tcp_retrans_total", "TCP retransmissions (count)", unit="count", layer="transport", kind="counter", osi_layer=4, category="transport", dimensions=["src", "dst", "flow"]),
    md("tcp_fast_retrans_total", "TCP fast retransmit", unit="count", layer="transport", kind="counter", osi_layer=4, category="transport", dimensions=["src", "dst", "flow"]),
    md("tcp_dup_acks_total", "TCP duplicate ACKs", unit="count", layer="transport", kind="counter", osi_layer=4, category="transport", dimensions=["src", "dst", "flow"]),
    md("tcp_handshake_success_pct", "TCP handshake success rate", unit="%", layer="transport", kind="ratio", osi_layer=4, category="transport", dimensions=["dst", "port"]),
    md("tcp_handshake_latency_ms", "TCP handshake latency", unit="ms", layer="transport", kind="gauge", osi_layer=4, category="transport", dimensions=["dst", "port"]),
    md("tcp_resets_total", "Resets (RST)", unit="count", layer="transport", kind="counter", osi_layer=4, category="transport", dimensions=["src", "dst", "flow"]),
    md("tcp_out_of_order_total", "TCP out-of-order", unit="count", layer="transport", kind="counter", osi_layer=4, category="transport", dimensions=["src", "dst", "flow"]),
    md("tcp_zero_window_total", "TCP zero window", unit="count", layer="transport", kind="counter", osi_layer=4, category="transport", dimensions=["src", "dst", "flow"]),
    md("tcp_window_scaling_anomalies_total", "TCP window scaling anomalies", unit="count", layer="transport", kind="counter", osi_layer=4, category="transport", dimensions=["src", "dst", "flow"]),
    md("udp_loss_pct", "UDP loss", unit="%", layer="transport", kind="ratio", osi_layer=4, category="transport", dimensions=["src", "dst", "flow"]),
    md("udp_jitter_ms", "UDP jitter", unit="ms", layer="transport", kind="gauge", osi_layer=4, category="transport", dimensions=["src", "dst", "flow"]),
    md("nat_table_util_pct", "NAT table utilization", unit="%", layer="transport", kind="ratio", osi_layer=4, category="nat",
       dimensions=["node", "nat_pool"]),
    md("nat_port_exhaustion_events_total", "NAT port exhaustion events", unit="count", layer="transport", kind="counter", osi_layer=4, category="nat", dimensions=["node", "nat_pool"]),
    md("nat_translation_failures_total", "NAT translation failures", unit="count", layer="transport", kind="counter", osi_layer=4, category="nat", dimensions=["node"]),
    md("lb_healthcheck_success_pct", "Load balancer health checks success", unit="%", layer="transport", kind="ratio", osi_layer=4, category="lb", dimensions=["lb", "pool", "backend"]),
    md("lb_connection_rate", "Load balancer connection rate", unit="count/s", layer="transport", kind="gauge", osi_layer=4, category="lb", dimensions=["lb", "vip"]),
    md("lb_concurrent_connections", "Load balancer concurrent connections", unit="count", layer="transport", kind="gauge", osi_layer=4, category="lb", dimensions=["lb", "vip"]),
    md("lb_backend_connect_errors_total", "LB backend connect errors", unit="count", layer="transport", kind="counter", osi_layer=4, category="lb", dimensions=["lb", "backend"]),
    md("lb_backend_timeouts_total", "LB backend timeouts", unit="count", layer="transport", kind="counter", osi_layer=4, category="lb", dimensions=["lb", "backend"]),

    # Existing transport metrics kept
    md("throughput_mbps", "Throughput", unit="Mbps", layer="transport", kind="gauge", osi_layer=4, category="performance", dimensions=["src", "dst"]),
    md("tcp_rtt_ms", "TCP RTT", unit="ms", layer="transport", kind="gauge", osi_layer=4, category="transport", dimensions=["src", "dst", "flow"]),
    md("ss_sockets_total", "Total sockets from ss -s", unit="count", layer="transport", kind="gauge", osi_layer=4, category="host", dimensions=["node"]),
    md("ss_tcp_states", "TCP states from ss -s", unit="count", layer="transport", kind="gauge", osi_layer=4, category="host", dimensions=["node"]),
    md("ss_udp_sockets_total", "UDP sockets from ss -s", unit="count", layer="transport", kind="gauge", osi_layer=4, category="host", dimensions=["node"]),
    md("ss_tcp_sockets_total", "TCP sockets from ss -s", unit="count", layer="transport", kind="gauge", osi_layer=4, category="host", dimensions=["node"]),
    md("ss_raw_sockets_total", "RAW sockets from ss -s", unit="count", layer="transport", kind="gauge", osi_layer=4, category="host", dimensions=["node"]),
    md("ss_inet_sockets_total", "INET sockets from ss -s", unit="count", layer="transport", kind="gauge", osi_layer=4, category="host", dimensions=["node"]),
    md("ss_frag_sockets_total", "FRAG sockets from ss -s", unit="count", layer="transport", kind="gauge", osi_layer=4, category="host", dimensions=["node"]),

    # /proc/net/snmp counters (kept)
    md("snmp_ip_in_receives", "IP InReceives", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_in_hdr_errors", "IP InHdrErrors", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_in_addr_errors", "IP InAddrErrors", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_forw_datagrams", "IP ForwDatagrams", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_in_unknown_protos", "IP InUnknownProtos", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_in_discards", "IP InDiscards", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_in_delivers", "IP InDelivers", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_out_requests", "IP OutRequests", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_out_discards", "IP OutDiscards", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_out_no_routes", "IP OutNoRoutes", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_reasm_timeout", "IP ReasmTimeout", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_reasm_reqds", "IP ReasmReqds", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_reasm_oks", "IP ReasmOKs", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_reasm_fails", "IP ReasmFails", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_frag_oks", "IP FragOKs", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_frag_fails", "IP FragFails", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_frag_creates", "IP FragCreates", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_ip_out_transmits", "IP OutTransmits", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_icmp_in_msgs", "ICMP InMsgs", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_icmp_out_msgs", "ICMP OutMsgs", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_icmp_in_errors", "ICMP InErrors", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_icmp_out_errors", "ICMP OutErrors", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_icmp_in_dest_unreachs", "ICMP InDestUnreachs", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_icmp_out_dest_unreachs", "ICMP OutDestUnreachs", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_icmp_in_time_excds", "ICMP InTimeExcds", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_icmp_out_time_excds", "ICMP OutTimeExcds", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_icmp_in_echo_reqs", "ICMP InEchos", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_icmp_out_echo_reps", "ICMP OutEchoReps", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_tcp_active_opens", "TCP ActiveOpens", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_tcp_passive_opens", "TCP PassiveOpens", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_tcp_attempt_fails", "TCP AttemptFails", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_tcp_estab_resets", "TCP EstabResets", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_tcp_curr_estab", "TCP CurrEstab", unit="count", layer="transport", kind="gauge", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_tcp_in_segs", "TCP InSegs", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_tcp_out_segs", "TCP OutSegs", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_tcp_retrans_segs", "TCP RetransSegs", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_tcp_in_errs", "TCP InErrs", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_tcp_out_rsts", "TCP OutRsts", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_tcp_in_csum_errors", "TCP InCsumErrors", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_udp_in_datagrams", "UDP InDatagrams", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_udp_no_ports", "UDP NoPorts", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_udp_in_errors", "UDP InErrors", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_udp_out_datagrams", "UDP OutDatagrams", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_udp_rcvbuf_errors", "UDP RcvbufErrors", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_udp_sndbuf_errors", "UDP SndbufErrors", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_udp_in_csum_errors", "UDP InCsumErrors", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_udp_ignored_multi", "UDP IgnoredMulti", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),
    md("snmp_udp_mem_errors", "UDP MemErrors", unit="count", layer="transport", kind="counter", osi_layer=4, category="snmp", dimensions=["node"]),

    # 5) Session (L5)
    md("tls_session_resumption_pct", "TLS session resumption rate", unit="%", layer="session", kind="ratio", osi_layer=5, category="tls", dimensions=["sni", "service"]),
    md("tls_renegotiations_total", "TLS renegotiations", unit="count", layer="session", kind="counter", osi_layer=5, category="tls", dimensions=["sni", "service"]),
    md("tls_handshake_failures_total", "TLS handshake failures (por SNI/cert)", unit="count", layer="session", kind="counter", osi_layer=5, category="tls", dimensions=["sni", "cert"]),
    md("vpn_sessions_active", "VPN sessions active", unit="count", layer="session", kind="gauge", osi_layer=5, category="vpn", dimensions=["profile", "tenant"]),
    md("vpn_session_establish_rate", "VPN session establish rate", unit="count/s", layer="session", kind="gauge", osi_layer=5, category="vpn", dimensions=["profile", "tenant"]),
    md("vpn_session_failures_total", "VPN session failures", unit="count", layer="session", kind="counter", osi_layer=5, category="vpn", dimensions=["profile", "tenant", "reason"]),
    md("aaa_auth_failures_total", "Falhas de autenticação AAA", unit="count", layer="session", kind="counter", osi_layer=5, category="aaa", dimensions=["realm", "reason"]),
    md("session_idle_timeouts_total", "Idle/timeout expirations", unit="count", layer="session", kind="counter", osi_layer=5, category="session", dimensions=["policy", "profile"]),
    md("fw_state_table_util_pct", "Firewall state table usage", unit="%", layer="session", kind="ratio", osi_layer=5, category="security", dimensions=["node"]),
    md("fw_state_table_drops_total", "Drops por overflow de state table", unit="count", layer="session", kind="counter", osi_layer=5, category="security", dimensions=["node"]),

    # 6) Presentation (L6)
    md("tls_handshake_latency_ms_p95", "TLS handshake latency p95", unit="ms", layer="presentation", kind="summary", osi_layer=6, category="tls", dimensions=["sni", "service"]),
    md("tls_handshake_latency_ms_p99", "TLS handshake latency p99", unit="ms", layer="presentation", kind="summary", osi_layer=6, category="tls", dimensions=["sni", "service"]),
    md("tls_version_connections_total", "Distribuição de versões TLS", unit="count", layer="presentation", kind="counter", osi_layer=6, category="tls", dimensions=["version", "sni"]),
    md("tls_cipher_connections_total", "Distribuição de ciphers", unit="count", layer="presentation", kind="counter", osi_layer=6, category="tls", dimensions=["cipher", "sni"]),
    md("cert_expiry_days", "Certificados: dias até expiração", unit="days", layer="presentation", kind="gauge", osi_layer=6, category="tls", dimensions=["cert", "sni"]),
    md("cert_validation_errors_total", "Certificados: validation errors", unit="count", layer="presentation", kind="counter", osi_layer=6, category="tls", dimensions=["cert", "sni"]),
    md("cert_chain_errors_total", "Certificados: chain errors", unit="count", layer="presentation", kind="counter", osi_layer=6, category="tls", dimensions=["cert", "sni"]),
    md("sni_mismatch_total", "SNI mismatch", unit="count", layer="presentation", kind="counter", osi_layer=6, category="tls", dimensions=["sni", "cert"]),
    md("compression_errors_total", "Erro de compressão (gzip/br)", unit="count", layer="presentation", kind="counter", osi_layer=6, category="encoding", dimensions=["algo"]),
    md("encoding_errors_total", "Erro de encoding/codec", unit="count", layer="presentation", kind="counter", osi_layer=6, category="encoding", dimensions=["codec"]),
    md("http2_negotiation_success_pct", "HTTP/2 negotiation success", unit="%", layer="presentation", kind="ratio", osi_layer=6, category="http", dimensions=["service"]),
    md("http3_quic_negotiation_success_pct", "HTTP/3 (QUIC) negotiation success", unit="%", layer="presentation", kind="ratio", osi_layer=6, category="http", dimensions=["service"]),
    md("quic_fallback_rate_pct", "HTTP/3 fallback rate", unit="%", layer="presentation", kind="ratio", osi_layer=6, category="http", dimensions=["service"]),

    # 7) Application (L7)
    md("app_rps", "Taxa de requisições (RPS/QPS)", unit="rps", layer="application", kind="gauge", osi_layer=7, category="app", dimensions=["service", "route"]),
    md("app_latency_ms_p95", "Latência p95 (app)", unit="ms", layer="application", kind="summary", osi_layer=7, category="app", dimensions=["service", "route"]),
    md("app_latency_ms_p99", "Latência p99 (app)", unit="ms", layer="application", kind="summary", osi_layer=7, category="app", dimensions=["service", "route"]),
    md("http_responses_total", "Códigos HTTP (por classe/rota)", unit="count", layer="application", kind="counter", osi_layer=7, category="http", dimensions=["service", "route", "code"]),
    md("http_errors_total", "HTTP errors (4xx/5xx)", unit="count", layer="application", kind="counter", osi_layer=7, category="http", dimensions=["service", "route", "code"]),
    md("dns_qps", "DNS QPS", unit="qps", layer="application", kind="gauge", osi_layer=7, category="dns", dimensions=["server", "zone"]),
    md("dns_latency_ms_p95", "DNS latency p95", unit="ms", layer="application", kind="summary", osi_layer=7, category="dns", dimensions=["server", "zone"]),
    md("dns_servfail_total", "DNS SERVFAIL", unit="count", layer="application", kind="counter", osi_layer=7, category="dns", dimensions=["server", "zone"]),
    md("dns_nxdomain_total", "DNS NXDOMAIN", unit="count", layer="application", kind="counter", osi_layer=7, category="dns", dimensions=["server", "zone"]),
    md("dns_cache_hit_ratio_pct", "DNS cache hit ratio", unit="%", layer="application", kind="ratio", osi_layer=7, category="dns", dimensions=["server"]),
    md("dhcp_success_pct", "DHCP success rate (DORA)", unit="%", layer="application", kind="ratio", osi_layer=7, category="dhcp", dimensions=["scope", "server"]),
    md("dhcp_dora_latency_ms", "DHCP DORA latency", unit="ms", layer="application", kind="gauge", osi_layer=7, category="dhcp", dimensions=["scope", "server"]),
    md("dhcp_pool_util_pct", "DHCP pool utilization", unit="%", layer="application", kind="ratio", osi_layer=7, category="dhcp", dimensions=["scope"]),
    md("dhcp_conflicts_total", "DHCP conflicts", unit="count", layer="application", kind="counter", osi_layer=7, category="dhcp", dimensions=["scope"]),
    md("ntp_offset_ms", "NTP offset/drift", unit="ms", layer="application", kind="gauge", osi_layer=7, category="ntp", dimensions=["server"]),
    md("ntp_drift_ppm", "NTP drift", unit="ppm", layer="application", kind="gauge", osi_layer=7, category="ntp", dimensions=["server"]),
    md("ntp_stratum_changes_total", "NTP stratum changes", unit="count", layer="application", kind="counter", osi_layer=7, category="ntp", dimensions=["server"]),
    md("ntp_reachability_pct", "NTP reachability", unit="%", layer="application", kind="ratio", osi_layer=7, category="ntp", dimensions=["server"]),
    md("http_ttfb_ms", "HTTP time-to-first-byte", unit="ms", layer="application", kind="gauge", osi_layer=7, category="http", dimensions=["service", "route"]),
    md("http_ttlb_ms", "HTTP time-to-last-byte", unit="ms", layer="application", kind="gauge", osi_layer=7, category="http", dimensions=["service", "route"]),
    md("http_payload_bytes_p95", "HTTP payload size p95", unit="bytes", layer="application", kind="summary", osi_layer=7, category="http", dimensions=["service", "route"]),
    md("grpc_status_total", "gRPC status codes", unit="count", layer="application", kind="counter", osi_layer=7, category="grpc", dimensions=["service", "method", "status"]),
    md("grpc_deadlines_exceeded_total", "gRPC deadlines exceeded", unit="count", layer="application", kind="counter", osi_layer=7, category="grpc", dimensions=["service", "method"]),
    md("db_connection_errors_total", "Database connection errors (alto nível)", unit="count", layer="application", kind="counter", osi_layer=7, category="db", dimensions=["db", "service"]),
    md("db_query_latency_ms_p95", "Database query latency p95 (alto nível)", unit="ms", layer="application", kind="summary", osi_layer=7, category="db", dimensions=["db", "service"]),

    # Control-plane (platform)
    md("controller_latency_ms", "Controller latency", unit="ms", layer="control", kind="gauge", category="control", dimensions=["controller", "endpoint"]),
    md("controller_conn_ok", "Controller connectivity", unit="bool", layer="control", kind="gauge", category="control", dimensions=["controller"]),
    md("of_channel_reconnects", "OpenFlow reconnects", unit="count", layer="control", kind="counter", category="control", dimensions=["switch"]),
    md("flows_installed", "Flows installed", unit="count", layer="control", kind="counter", category="control", dimensions=["controller", "switch"]),
    md("flows_removed", "Flows removed", unit="count", layer="control", kind="counter", category="control", dimensions=["controller", "switch"]),
    md("cpu_util_pct", "CPU utilization", unit="%", layer="control", kind="gauge", category="host", dimensions=["node"]),
    md("mem_util_pct", "Memory utilization", unit="%", layer="control", kind="gauge", category="host", dimensions=["node"]),

    # Dataplane (platform)
    md("openflow_flow_packets", "Flow packets", unit="packets", layer="dataplane", kind="counter", category="dataplane", dimensions=["switch", "table", "flow"]),
    md("openflow_flow_bytes", "Flow bytes", unit="bytes", layer="dataplane", kind="counter", category="dataplane", dimensions=["switch", "table", "flow"]),
    md("table_hits", "Table hits", unit="count", layer="dataplane", kind="counter", category="dataplane", dimensions=["switch", "table"]),
    md("table_misses", "Table misses", unit="count", layer="dataplane", kind="counter", category="dataplane", dimensions=["switch", "table"]),
    md("port_rx_pkts", "Port RX packets", unit="packets", layer="dataplane", kind="counter", category="dataplane", dimensions=["switch", "port"]),
    md("port_tx_pkts", "Port TX packets", unit="packets", layer="dataplane", kind="counter", category="dataplane", dimensions=["switch", "port"]),
    md("port_rx_drops", "Port RX drops", unit="packets", layer="dataplane", kind="counter", category="dataplane", dimensions=["switch", "port"]),
    md("port_tx_drops", "Port TX drops", unit="packets", layer="dataplane", kind="counter", category="dataplane", dimensions=["switch", "port"]),
    md("flow_bytes", "Flow byte counter", unit="bytes", layer="dataplane", kind="counter", category="dataplane", dimensions=["src", "dst", "5tuple"]),
    md("flow_packets", "Flow packet counter", unit="packets", layer="dataplane", kind="counter", category="dataplane", dimensions=["src", "dst", "5tuple"]),
    md("flow_duration_sec", "Flow duration", unit="s", layer="dataplane", kind="gauge", category="dataplane", dimensions=["src", "dst", "5tuple"]),

    # Transversal: capacity / congestion
    md("interface_util_p95_pct", "Interface utilization p95", unit="%", layer="service", kind="derived", category="capacity", dimensions=["node", "interface"]),
    md("interface_headroom_pct", "Interface headroom", unit="%", layer="service", kind="derived", category="capacity", dimensions=["node", "interface"]),
    md("queue_depth", "Queue depth", unit="count", layer="service", kind="gauge", category="capacity", dimensions=["node", "interface", "queue", "qos_class"]),
    md("buffer_occupancy_pct", "Buffer occupancy", unit="%", layer="service", kind="gauge", category="capacity", dimensions=["node", "asic"]),
    md("ecn_marks_total", "ECN marks", unit="count", layer="service", kind="counter", category="capacity", dimensions=["node", "interface", "qos_class"]),
    md("elephant_flows_total", "Elephant flows (classificação)", unit="count", layer="service", kind="derived", category="capacity", dimensions=["node", "app"]),
    md("mice_flows_total", "Mice flows (classificação)", unit="count", layer="service", kind="derived", category="capacity", dimensions=["node", "app"]),
    md("hotspot_score", "Hotspot score (links/ASICs com maior utilização/drops)", unit=None, layer="service", kind="derived", category="capacity", dimensions=["node", "interface", "asic"]),

    # Transversal: reliability / errors
    md("slo_error_budget_remaining_pct", "Error budget restante do SLO", unit="%", layer="service", kind="derived", category="reliability", dimensions=["slo", "service"]),
    md("incident_rate", "Taxa de incidentes", unit="count/s", layer="service", kind="derived", category="reliability", dimensions=["service"]),
    md("flap_storm_events_total", "Flap storms", unit="count", layer="service", kind="counter", category="reliability", dimensions=["node", "interface"]),
    md("config_drift_score", "Config drift vs golden config", unit=None, layer="service", kind="derived", category="reliability", dimensions=["node"]),

    # Transversal: security / threats
    md("firewall_denies_total", "Firewall/IDS denies por policy", unit="count", layer="service", kind="counter", category="security", dimensions=["policy", "rule_id", "node"]),
    md("scan_spikes_total", "Picos de scans", unit="count", layer="service", kind="counter", category="security", dimensions=["src", "dst", "port"]),
    md("ddos_syn_rate_pps", "DDoS signal: SYN rate", unit="pps", layer="service", kind="gauge", category="security", dimensions=["dst", "service"]),
    md("ddos_udp_flood_pps", "DDoS signal: UDP flood indicators", unit="pps", layer="service", kind="gauge", category="security", dimensions=["dst", "service"]),
    md("abnormal_pps", "PPS anormal", unit="pps", layer="service", kind="derived", category="security", dimensions=["node", "interface"]),
    md("anomaly_new_asns_total", "Anomalias: novos ASNs", unit="count", layer="service", kind="counter", category="security", dimensions=["asn", "prefix"]),
    md("anomaly_new_countries_total", "Anomalias: novos países", unit="count", layer="service", kind="counter", category="security", dimensions=["country", "service"]),
    md("anomaly_new_services_total", "Anomalias: novos serviços", unit="count", layer="service", kind="counter", category="security", dimensions=["service"]),
    md("anomaly_new_ports_total", "Anomalias: novas portas", unit="count", layer="service", kind="counter", category="security", dimensions=["port", "proto"]),
    md("auth_failures_total", "Falhas AAA/VPN (agregado)", unit="count", layer="service", kind="counter", category="security", dimensions=["realm", "profile"]),
    md("cert_errors_total", "Cert errors (agregado)", unit="count", layer="service", kind="counter", category="security", dimensions=["sni", "cert"]),
]


def metric_definitions() -> List[MetricDefinition]:
    # Return a copy to keep callers from mutating the canonical catalog.
    return list(METRIC_CATALOG)
