from __future__ import annotations

from typing import Any, Dict, Protocol, runtime_checkable


@runtime_checkable
class ExperimentRunner(Protocol):
    def name(self) -> str: ...
    def supported_controllers(self) -> list[str]: ...
    async def setup(self, context: Dict[str, Any]) -> None: ...
    async def run(self, context: Dict[str, Any]) -> None: ...
    async def teardown(self, context: Dict[str, Any]) -> None: ...


@runtime_checkable
class MetricCollector(Protocol):
    def name(self) -> str: ...
    def supported_metrics(self) -> list[str]: ...
    async def start(self, context: Dict[str, Any]) -> None: ...
    async def collect(self, context: Dict[str, Any]) -> Dict[str, Any]: ...
    async def stop(self, context: Dict[str, Any]) -> None: ...


@runtime_checkable
class TrafficGenerator(Protocol):
    def name(self) -> str: ...
    def supported_protocols(self) -> list[str]: ...
    async def start(self, context: Dict[str, Any]) -> None: ...
    async def stop(self, context: Dict[str, Any]) -> None: ...


def is_experiment_runner(obj: Any) -> bool:
    return isinstance(obj, ExperimentRunner)


def is_metric_collector(obj: Any) -> bool:
    return isinstance(obj, MetricCollector)


def is_traffic_generator(obj: Any) -> bool:
    return isinstance(obj, TrafficGenerator)
