export type EntityKind = "switch" | "host" | "controller";

export type MetricCategory = "Saúde" | "Capacidade" | "Erros" | "Performance";
export type MetricType = "Gauge" | "Counter";

export type MetricLayer =
  | "L0"
  | "L1"
  | "L2"
  | "L3"
  | "L4"
  | "L5"
  | "L6"
  | "L7"
  | "Control Plane"
  | "Dataplane";

export type MetricKind = "bool" | "number";

export type MetricDimension = "node" | "interface";

export type MetricSpec = {
  key: string;
  name: string;
  layer: MetricLayer;
  category: MetricCategory;
  type: MetricType;
  kind: MetricKind;
  unit?: string;
  dimension: MetricDimension;
  entityKinds: EntityKind[];
  sim: {
    initial: number;
    step: number;
    min: number;
    max: number;
  };
};

export const LAYERS: MetricLayer[] = [
  "L0",
  "L1",
  "L2",
  "L3",
  "L4",
  "L5",
  "L6",
  "L7",
  "Control Plane",
  "Dataplane",
];

export const CATEGORIES: MetricCategory[] = ["Saúde", "Capacidade", "Erros", "Performance"];
export const TYPES: MetricType[] = ["Gauge", "Counter"];

// Explicit per-layer configuration: each tab loads its own list.
// Keys/names/units/categories here are meant to mirror the technical metric table.
export const LAYER_METRICS: Record<MetricLayer, MetricSpec[]> = {
  L0: [
    {
      key: "if_link_up",
      name: "if_link_up",
      layer: "L0",
      category: "Saúde",
      type: "Gauge",
      kind: "bool",
      unit: "bool",
      dimension: "interface",
      entityKinds: ["switch", "host"],
      sim: { initial: 1, step: 1, min: 0, max: 1 },
    },
    {
      key: "if_errors",
      name: "if_errors",
      layer: "L0",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "pkts",
      dimension: "interface",
      entityKinds: ["switch", "host"],
      sim: { initial: 0, step: 6, min: 0, max: 5000 },
    },
    {
      key: "optic_rx_dbm",
      name: "optic_rx_dbm",
      layer: "L0",
      category: "Saúde",
      type: "Gauge",
      kind: "number",
      unit: "dBm",
      dimension: "interface",
      entityKinds: ["switch"],
      sim: { initial: -3.2, step: 0.25, min: -18, max: 1 },
    },
    {
      key: "optic_tx_dbm",
      name: "optic_tx_dbm",
      layer: "L0",
      category: "Saúde",
      type: "Gauge",
      kind: "number",
      unit: "dBm",
      dimension: "interface",
      entityKinds: ["switch"],
      sim: { initial: -2.1, step: 0.2, min: -12, max: 2 },
    },
    {
      key: "if_speed_mbps",
      name: "if_speed_mbps",
      layer: "L0",
      category: "Capacidade",
      type: "Gauge",
      kind: "number",
      unit: "Mbps",
      dimension: "interface",
      entityKinds: ["switch", "host"],
      sim: { initial: 1000, step: 0, min: 10, max: 400000 },
    },
    {
      key: "if_crc_errors",
      name: "if_crc_errors",
      layer: "L0",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "frames",
      dimension: "interface",
      entityKinds: ["switch"],
      sim: { initial: 0, step: 3, min: 0, max: 10000 },
    },
  ],

  L1: [
    {
      key: "mac_table_size",
      name: "mac_table_size",
      layer: "L1",
      category: "Capacidade",
      type: "Gauge",
      kind: "number",
      unit: "entries",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 420, step: 12, min: 0, max: 16000 },
    },
    {
      key: "link_util_pct",
      name: "link_util_pct",
      layer: "L1",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "%",
      dimension: "interface",
      entityKinds: ["switch", "host"],
      sim: { initial: 22, step: 6, min: 0, max: 100 },
    },
    {
      key: "stp_topology_changes",
      name: "stp_topology_changes",
      layer: "L1",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "events",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 0, step: 1, min: 0, max: 1000 },
    },
    {
      key: "vlan_active_count",
      name: "vlan_active_count",
      layer: "L1",
      category: "Capacidade",
      type: "Gauge",
      kind: "number",
      unit: "vlans",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 4, step: 1.2, min: 0, max: 4094 },
    },
    {
      key: "lldp_neighbors",
      name: "lldp_neighbors",
      layer: "L1",
      category: "Saúde",
      type: "Gauge",
      kind: "number",
      unit: "n",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 3, step: 0.6, min: 0, max: 64 },
    },
    {
      key: "port_rx_bps",
      name: "port_rx_bps",
      layer: "L1",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "bps",
      dimension: "interface",
      entityKinds: ["switch"],
      sim: { initial: 3.2e8, step: 9.0e7, min: 0, max: 1.0e10 },
    },
    {
      key: "port_tx_bps",
      name: "port_tx_bps",
      layer: "L1",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "bps",
      dimension: "interface",
      entityKinds: ["switch"],
      sim: { initial: 2.6e8, step: 8.0e7, min: 0, max: 1.0e10 },
    },
  ],

  L2: [
    {
      key: "route_count",
      name: "route_count",
      layer: "L2",
      category: "Capacidade",
      type: "Gauge",
      kind: "number",
      unit: "routes",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 64, step: 2.2, min: 0, max: 500000 },
    },
    {
      key: "bgp_session_up",
      name: "bgp_session_up",
      layer: "L2",
      category: "Saúde",
      type: "Gauge",
      kind: "bool",
      unit: "bool",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 1, step: 1, min: 0, max: 1 },
    },
    {
      key: "arp_cache_entries",
      name: "arp_cache_entries",
      layer: "L2",
      category: "Capacidade",
      type: "Gauge",
      kind: "number",
      unit: "entries",
      dimension: "node",
      entityKinds: ["host", "switch"],
      sim: { initial: 18, step: 2.5, min: 0, max: 4096 },
    },
    {
      key: "ipv4_forward_drops",
      name: "ipv4_forward_drops",
      layer: "L2",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "pkts",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 0, step: 4, min: 0, max: 200000 },
    },
    {
      key: "icmp_unreach_total",
      name: "icmp_unreach_total",
      layer: "L2",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "pkts",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 0, step: 1, min: 0, max: 20000 },
    },
    {
      key: "routing_table_size",
      name: "routing_table_size",
      layer: "L2",
      category: "Capacidade",
      type: "Gauge",
      kind: "number",
      unit: "routes",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 64, step: 2.2, min: 0, max: 500000 },
    },
  ],

  L3: [
    {
      key: "tcp_retrans_pct",
      name: "tcp_retrans_pct",
      layer: "L3",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "%",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 0.8, step: 0.5, min: 0, max: 100 },
    },
    {
      key: "udp_loss_pct",
      name: "udp_loss_pct",
      layer: "L3",
      category: "Erros",
      type: "Gauge",
      kind: "number",
      unit: "%",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 0.2, step: 0.25, min: 0, max: 100 },
    },
    {
      key: "throughput_mbps",
      name: "throughput_mbps",
      layer: "L3",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "Mbps",
      dimension: "node",
      entityKinds: ["host", "switch"],
      sim: { initial: 420, step: 35, min: 0, max: 150000 },
    },
    {
      key: "tcp_retrans_total",
      name: "tcp_retrans_total",
      layer: "L3",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "segs",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 0, step: 12, min: 0, max: 1000000 },
    },
    {
      key: "tcp_rtt_ms",
      name: "tcp_rtt_ms",
      layer: "L3",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "ms",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 18, step: 2.4, min: 1, max: 300 },
    },
    {
      key: "udp_rx_drops_total",
      name: "udp_rx_drops_total",
      layer: "L3",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "pkts",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 0, step: 4, min: 0, max: 300000 },
    },
    {
      key: "socket_open_fds",
      name: "socket_open_fds",
      layer: "L3",
      category: "Capacidade",
      type: "Gauge",
      kind: "number",
      unit: "fds",
      dimension: "node",
      entityKinds: ["host", "controller"],
      sim: { initial: 220, step: 20, min: 0, max: 200000 },
    },
  ],

  L4: [
    {
      key: "sessions_established",
      name: "sessions_established",
      layer: "L4",
      category: "Capacidade",
      type: "Gauge",
      kind: "number",
      unit: "n",
      dimension: "node",
      entityKinds: ["host", "controller"],
      sim: { initial: 38, step: 6, min: 0, max: 200000 },
    },
    {
      key: "session_reset_total",
      name: "session_reset_total",
      layer: "L4",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "events",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 0, step: 3, min: 0, max: 500000 },
    },
  ],

  L5: [
    {
      key: "tls_handshake_latency",
      name: "tls_handshake_latency",
      layer: "L5",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "ms",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 24, step: 4, min: 1, max: 800 },
    },
    {
      key: "tls_handshake_fail_total",
      name: "tls_handshake_fail_total",
      layer: "L5",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "fails",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 0, step: 1, min: 0, max: 100000 },
    },
    {
      key: "tls_handshake_ms",
      name: "tls_handshake_ms",
      layer: "L5",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "ms",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 24, step: 4, min: 1, max: 800 },
    },
  ],

  L6: [
    {
      key: "cpu_pct",
      name: "cpu_pct",
      layer: "L6",
      category: "Saúde",
      type: "Gauge",
      kind: "number",
      unit: "%",
      dimension: "node",
      entityKinds: ["host", "controller"],
      sim: { initial: 18, step: 6, min: 0, max: 100 },
    },
    {
      key: "ram_used_pct",
      name: "ram_used_pct",
      layer: "L6",
      category: "Saúde",
      type: "Gauge",
      kind: "number",
      unit: "%",
      dimension: "node",
      entityKinds: ["host", "controller"],
      sim: { initial: 42, step: 5, min: 0, max: 100 },
    },
    {
      key: "app_latency_ms",
      name: "app_latency_ms",
      layer: "L6",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "ms",
      dimension: "node",
      entityKinds: ["host", "controller"],
      sim: { initial: 32, step: 8, min: 1, max: 2000 },
    },
    {
      key: "app_latency_ms_p95",
      name: "app_latency_ms_p95",
      layer: "L6",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "ms",
      dimension: "node",
      entityKinds: ["host", "controller"],
      sim: { initial: 85, step: 18, min: 1, max: 6000 },
    },
    {
      key: "http_responses_total",
      name: "http_responses_total",
      layer: "L6",
      category: "Performance",
      type: "Counter",
      kind: "number",
      unit: "req",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 100000, step: 4500, min: 0, max: 1.0e12 },
    },
    {
      key: "http_5xx_total",
      name: "http_5xx_total",
      layer: "L6",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "req",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 0, step: 2, min: 0, max: 1000000 },
    },
  ],

  L7: [
    {
      key: "dns_resolve_ms",
      name: "dns_resolve_ms",
      layer: "L7",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "ms",
      dimension: "node",
      entityKinds: ["host"],
      sim: { initial: 6, step: 1.2, min: 0.2, max: 250 },
    },
    {
      key: "service_error_rate_pct",
      name: "service_error_rate_pct",
      layer: "L7",
      category: "Erros",
      type: "Gauge",
      kind: "number",
      unit: "%",
      dimension: "node",
      entityKinds: ["host", "controller"],
      sim: { initial: 0.4, step: 0.3, min: 0, max: 100 },
    },
    {
      key: "e2e_path_availability",
      name: "e2e_path_availability",
      layer: "L7",
      category: "Saúde",
      type: "Gauge",
      kind: "bool",
      unit: "bool",
      dimension: "node",
      entityKinds: ["host", "switch"],
      sim: { initial: 1, step: 1, min: 0, max: 1 },
    },
  ],

  "Control Plane": [
    {
      key: "controller_latency",
      name: "controller_latency",
      layer: "Control Plane",
      category: "Performance",
      type: "Gauge",
      kind: "number",
      unit: "ms",
      dimension: "node",
      entityKinds: ["controller"],
      sim: { initial: 8, step: 2.2, min: 0.2, max: 800 },
    },
    {
      key: "flows_installed",
      name: "flows_installed",
      layer: "Control Plane",
      category: "Performance",
      type: "Counter",
      kind: "number",
      unit: "flows",
      dimension: "node",
      entityKinds: ["controller"],
      sim: { initial: 1200, step: 80, min: 0, max: 1.0e9 },
    },
    {
      key: "channel_reconnects_total",
      name: "channel_reconnects_total",
      layer: "Control Plane",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "events",
      dimension: "node",
      entityKinds: ["controller"],
      sim: { initial: 0, step: 1, min: 0, max: 100000 },
    },
    {
      key: "controller_heartbeat_up",
      name: "controller_heartbeat_up",
      layer: "Control Plane",
      category: "Saúde",
      type: "Gauge",
      kind: "bool",
      unit: "bool",
      dimension: "node",
      entityKinds: ["controller"],
      sim: { initial: 1, step: 1, min: 0, max: 1 },
    },
    {
      key: "socket_open_fds",
      name: "socket_open_fds",
      layer: "Control Plane",
      category: "Capacidade",
      type: "Gauge",
      kind: "number",
      unit: "fds",
      dimension: "node",
      entityKinds: ["controller"],
      sim: { initial: 220, step: 20, min: 0, max: 200000 },
    },
  ],

  Dataplane: [
    {
      key: "table_hits",
      name: "table_hits",
      layer: "Dataplane",
      category: "Performance",
      type: "Counter",
      kind: "number",
      unit: "hits",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 5.5e6, step: 2.5e5, min: 0, max: 1.0e12 },
    },
    {
      key: "table_hits_total",
      name: "table_hits_total",
      layer: "Dataplane",
      category: "Performance",
      type: "Counter",
      kind: "number",
      unit: "hits",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 5.5e6, step: 2.5e5, min: 0, max: 1.0e12 },
    },
    {
      key: "table_miss_total",
      name: "table_miss_total",
      layer: "Dataplane",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "miss",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 1200, step: 180, min: 0, max: 1.0e9 },
    },
    {
      key: "port_rx_drops",
      name: "port_rx_drops",
      layer: "Dataplane",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "pkts",
      dimension: "interface",
      entityKinds: ["switch"],
      sim: { initial: 0, step: 8, min: 0, max: 100000 },
    },
    {
      key: "port_tx_drops",
      name: "port_tx_drops",
      layer: "Dataplane",
      category: "Erros",
      type: "Counter",
      kind: "number",
      unit: "pkts",
      dimension: "interface",
      entityKinds: ["switch"],
      sim: { initial: 0, step: 6, min: 0, max: 100000 },
    },
    {
      key: "flow_packets",
      name: "flow_packets",
      layer: "Dataplane",
      category: "Performance",
      type: "Counter",
      kind: "number",
      unit: "pkts",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 2.4e8, step: 2.2e6, min: 0, max: 1.0e15 },
    },
    {
      key: "flow_bytes_total",
      name: "flow_bytes_total",
      layer: "Dataplane",
      category: "Performance",
      type: "Counter",
      kind: "number",
      unit: "bytes",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 9.0e9, step: 1.1e8, min: 0, max: 1.0e15 },
    },
    {
      key: "pipeline_util_pct",
      name: "pipeline_util_pct",
      layer: "Dataplane",
      category: "Capacidade",
      type: "Gauge",
      kind: "number",
      unit: "%",
      dimension: "node",
      entityKinds: ["switch"],
      sim: { initial: 34, step: 9, min: 0, max: 100 },
    },
  ],
};

export const METRICS_CATALOG: MetricSpec[] = Object.values(LAYER_METRICS).flat();

export function getLayerMetrics(layer: MetricLayer) {
  return LAYER_METRICS[layer] ?? [];
}

export function prettyEntityKind(kind: EntityKind) {
  if (kind === "switch") return "Switch";
  if (kind === "host") return "Host";
  return "Controlador";
}
